# Generated by Django 5.0.3 on 2024-11-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('acteur', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=255)),
                ('evaluation', models.FloatField()),
                ('trailer', models.FileField(upload_to='static/video/trailer')),
                ('posteur', models.ImageField(upload_to='static/img/film/')),
                ('commentaires', models.CharField(max_length=255)),
            ],
        ),
    ]
