# Generated by Django 5.0.3 on 2024-11-08 03:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=3)),
                ('acteur', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=255)),
                ('evaluation', models.FloatField()),
                ('trailer', models.FileField(upload_to='static/video/trailer')),
                ('posteur', models.ImageField(upload_to='static/img/film/')),
                ('commentaires', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id_proj', models.AutoField(primary_key=True, serialize=False)),
                ('type_proj', models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('horror', 'Horror')], max_length=20)),
                ('date', models.CharField(max_length=255)),
                ('heure', models.CharField(max_length=255)),
                ('paf', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='cinetix.film')),
            ],
        ),
    ]
