# Generated by Django 5.0.3 on 2024-03-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('acteur', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=255)),
                ('evaluation', models.FloatField()),
                ('trailer', models.CharField(max_length=255)),
                ('posteur', models.CharField(max_length=255)),
                ('commentaires', models.CharField(max_length=255)),
            ],
        ),
    ]
