# Generated by Django 5.0.3 on 2024-11-01 05:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id_proj', models.AutoField(primary_key=True, serialize=False)),
                ('type_proj', models.CharField(max_length=255)),
                ('timings', models.CharField(max_length=255)),
                ('place_proj', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=92)),
                ('paf', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='cinetix.film')),
            ],
        ),
    ]
