# Generated by Django 5.0.3 on 2024-11-01 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetix', '0002_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='acteur',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, default=list, size=5),
        ),
        migrations.AlterField(
            model_name='film',
            name='commentaires',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=100),
        ),
    ]
