# Generated by Django 5.0.3 on 2024-11-02 02:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetix', '0003_alter_film_acteur_alter_film_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='acteur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='commentaires',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('thriller', 'Thriller'), ('horror', 'Horror')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
