# Generated by Django 5.0.3 on 2024-11-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetix', '0004_alter_film_acteur_alter_film_commentaires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(max_length=255),
        ),
    ]
